### ISSUE TITLE
Can we get a version without xaml? 

### ISSUE THREAD

**Issue by forki** [Prolucid/Elmish.WPF#1]
Something that uses functions like elmish.react? Would that be possible?

**Comment by 2sComplement** [comment]
We tried to build a version like this, but writing WPF components programmatically is not a good option. XAML is by far the best way to create WPF views. If we were to do something more along the 'react' lines WPF would likely not be the way to go (WinForms perhaps?).

**Comment by ReedCopsey** [comment]
I had the same feeling when doing Gjallarhorn (which is very similar)
