### ISSUE TITLE
Only one subscription is allowed

### ISSUE THREAD

**Issue by isaacabraham** [Prolucid/Elmish.WPF#11]
If you make two subscriptions using the `withSubscription` helper, the first is silently dropped.

**Comment by et1975** [comment]
The idea is to combine subscriptions yourself, same as `update` and `init`.

**Comment by forki** [comment]
Ok so we should let it fail? Just to avoid confusion

**Comment by isaacabraham** [comment]
Confirmed that combining two `Sub` functions works.

Perhaps this should be documented, somehow encoded in the type system, or simply throw an exception if the subscription channel is already used, to prevent people trying to add multiple subscriptions - otherwise they get silently throw away.

**Comment by 2sComplement** [comment]
Should this issue be in the [Elmish](https://github.com/fable-elmish/elmish) repo?

**Comment by et1975** [comment]
>Should this issue be in the Elmish repo?

Yes, please reopen in Elmish if you feel this needs to be solved.

**Comment by forki** [comment]
https://github.com/fable-elmish/elmish/issues/107
