### ISSUE TITLE
[Question] Use a strongly typed ViewModel

### ISSUE THREAD

**Issue by 0x53A** [Prolucid/Elmish.WPF#13]
Hi,

I have to admit that I haven't yet had much time to play with it, I just peeked a bit at the samples.
Do you think it would be possible to base the ViewModel that's passed to the view on something strongly typed?

Rider (and to a lesser degree VS) has support for IntelliSense and CodeCompletion inside Xaml. Supporting that would help a lot to avoid typos (or missed refactorings) inside the views.

I'm not  quite sure how the programming model for that could look. One idea may be to define an interface, which is used at design time. Then at runtime, when the viewModel is filled, it is checked that each property also exists in the interface.

Taking the example from the readme:

```F#
    let view _ _ = 
        let clockViewBinding : ViewBindings<ClockModel,ClockMsg> =
            [ "Time" |> Binding.oneWay (fun m -> m.Time) ]

        [ "Increment" |> Binding.cmd (fun m -> Increment)
          "Decrement" |> Binding.cmdIf (fun m -> Decrement) (fun m -> m.StepSize = 1)
          "Count" |> Binding.oneWay (fun m -> m.Count)
          "StepSize" |> Binding.twoWay (fun m -> (double m.StepSize)) (fun v m -> v |> int |> SetStepSize)
          "Clock" |> Binding.vm (fun m -> m.Clock) clockViewBinding ClockMsg ]
```

For this I would predefine an interface

```F#
type IMyViewModel =
  abstract Time : DateTime
  abstract Increment : ICommand
  abstract Decrement: ICommand
  abstract Count: int
...
```

Then if I wrote ``"Incrmnt" |> Binding.cmd (fun m -> Increment)`` by mistake, it would fail (or at least print to debug output) that ``Incrmnt`` is not defined in the interface.

---------------

My broad wish is just to be able to use a strongly typed view-model,  there is probably a better solution than my rambling above. =)

**Comment by BentTranberg** [comment]
Can FsXaml and Elmish.WPF in combination offer something in this regard?

**Comment by 2sComplement** [comment]
Intellisense would be nice in XAML, but the ViewModel cannot be strongly typed since it is built dynamically based on the Elmish model.
I could see something being done with the design-time DataContext being set to the Elmish model type. Would need to play around with that to provide a sample.

**Comment by 2sComplement** [comment]
I added a [sample](https://github.com/Prolucid/Elmish.WPF/blob/master/src/Samples/Elmish.Samples.DesignDataContext/MainWindow.xaml#L8) to show how this can be done. Let me know if there are any questions.

**Comment by BentTranberg** [comment]
It compiles when I do this in my own demo, but I get this error almost immediately when I start to edit the xaml, and it goes away again when I build or rebuild. Using VS 2017 15.2 (26430.15) and Visual F# nightly build 15.4.1.17071101, and FsXaml 3.1.6.

`Type d:DesignInstance is used like a markup extension but does not derive from MarkupExtension.`

**Comment by BentTranberg** [comment]
I suspect Reed Copsey's [Christmas Trees in WPF, 2017 Update](http://reedcopsey.com/2017/12/14/christmas-trees-in-wpf-2017-update/) can be relevant here. A "view model" is used, and magic strings are replaced with quotations.

**Comment by cmeeren** [comment]
When F#'s `nameof` operator comes out of preview, it will hopefully support using instance members without an instance, see https://github.com/dotnet/fsharp/pull/6809#issuecomment-519396979 and following comments. That would solve this particular issue, since you could do

```f#
nameof IMyViewModel.Increment |> Binding.cmd ...
```

**Comment by bender2k14** [comment]
In the meantime, I have been using this hack by Tomas Petricek:
https://stackoverflow.com/questions/48304398/is-there-an-equivalent-of-cs-nameof-in-f/48311816#48311816
