### ISSUE TITLE
Access to WPF Application instance

### ISSUE THREAD

**Issue by BentTranberg** [Prolucid/Elmish.WPF#14]
I wanted to use Application.DispatcherUnhandledException. In Program.fs of Elmish.WPF we can see the application object being created, but not exposed in any way. However, it is called with "window" - that would be the main window in this case - as argument. I added a handler to the main window's Loaded event, and in that handler Application.Current is available (no longer null, to be precise) and its properties can be set, among them DispatcherUnhandledException. In that handler, the argument property "Handled" can be set to true to prevent further processing of the exception, and so hopefully keep the application running. Many developers choose to implement a dialog with Ignore/Abort or something in this handler, and also logging of unhandled exceptions. I also have a habit of setting app.ShutdownMode to OnMainWindowClose, since I believe that's what most users would expect.

Does this make sense? Is there another more elegant way to access the application object? If not, should Elmish.WPF somehow expose the application object?

**Comment by et1975** [comment]
Regardless of what @2sComplement may suggest, Elmish approach in general is in line with "railway-oriented" programming - the functionality that does things (and consequently may throw) should be invoked via `Cmd` module functions (`ofFunc`, etc). They handle the exceptions by converting them to messages, which you handle like any other message in your `update`. The idea is to eliminate unhandled exceptions and handle failure scenarios explicitly.

**Comment by BentTranberg** [comment]
I appreciate what you explain, @et1975, and of course I do not regard unhandled exceptions as part of the normal program flow. They are by definition programming errors, and ideally should not occur. Nevertheless we can expect such errors to occur regardless of which tool, library, framework or language is in use - including Elmish.WPF - and so we must somehow also be able to handle them. The "unhandled exception handler" is the last safety net, and a valuable tool during development. From a pragmatic viewpoint I believe this is complimentary and not contradictory to the modern approaches you are referring to. Thanks for the info - useful right now since I'm new to all of this Elmish stuff, and I have to learn as I go.

**Comment by BentTranberg** [comment]
Thanks for the Ninja edit @et1975. That is what I was looking for, and I needed your explanation to understand how to use it. It works just as expected.

After some experimentation I see the following two behaviors.

I need onError to log any exception originating from the update function, or else Elmish.WPF will silence them. In any case the application continues to run happily if the error didn't corrupt it.

I also need Application.DispatcherUnhandledException (with Handled=true) to handle exceptions originating from the "fun" functions that I have put in the view function. If not using this, then the exception escapes entirely, and is finally caught by a try-with that I have put around the startup code. In short, the application blows up, but at least I get to log the exception. If using the DispatcherUnhandledException handler however, the application can continue to run happily if the error didn't corrupt it.

To conclude, I am very happy with the way it works now, but there is perhaps a chance for improvement by somehow exposing the application object.

How about an alternative to runWindow? You could have `runAppAndWindow app window`, the point being that you could create the application object yourself, just as you do with the window. This will perhaps make it easier to use FsXaml in combination with Elmish.WPF, if somebody wants to do that. You could then use the FsXaml type provider to create the application object as well as the window, and hand them both to Elmish.WPF.

**Comment by 2sComplement** [comment]
As per @et1975, unhandled exceptions will go through `Program.onError`, which is now exposed through `Program.withExceptionHandler`. Also included in a [sample](https://github.com/Prolucid/Elmish.WPF/blob/master/src/Samples/Elmish.Samples.Performance/Program.fs#L65).
