### ISSUE TITLE
WPF Commanding support

### ISSUE THREAD

**Issue by TheJayMann** [Prolucid/Elmish.WPF#16]
I have been thinking about the best way commanding support could be added to this project.  WPF Commanding has mostly been abandoned in MVVM style applications in favor of command binding.

WPF Commanding (RoutedCommands) originally served two purposes.  First was to be able to map multiple command sources (buttons, menus, toolbars, keyboard shortcuts, and mouse gestures) to the same command.  MVVM supports this same scenario by simply binding the various command sources to the same command.

However, the second purpose was to be able to map a single command to multiple command targets, allowing different functionality based on which target is receiving the command.  A good example of this would be a text editor application with a folder view, where one may want to be able to copy text in the editor, while also being able to copy a file or folder in the folder view. By binding the ApplicationCommands.Copy command to the command sources, the built in text editor control already knows how to handle the Copy command, thus you don't need to code anything.  However, if using the built in TreeView to display a folder view, it does not handle Copy command.  The typical way to do this in classic WPF would be to add a command binding, which would bind event handlers defined in the code behind to the commands for the command target. This approach does not work too well for either MVVM style nor Elm style.

Given an instance of the UIElement which will act as a command target, two (or four) functions which will act as event handlers for Execute and CanExcecute (and Preview*), and the RoutedCommand for responding, it would be trivial to create a CommandBinding and add it to the CommandBindings collection of the UIElement.

I have been thinking about how the public API could be defined to allow for this design.  First, it must be possible to get an instance of the UIElement.  My thought would be to create an attached property.   The value of this property would be a string which would contain the name of the command binding specified in the view binding.  For the view bindings, a new function `routedCommands` with the definition `(RoutedCommand * Execute<'model,'msg> * CanExecute<'model>) list -> string -> ViewBinding<'model,'msg>`. This would be a list of commands, along with the functions to execute when the command is invoked, as well as a name so they can be discovered via the attached property.

As an example:
```fsharp
"FolderViewCommands"
  |> Binding.routedCommands [
    ApplicationCommands.Copy, copyFile, canCopyFile
    ApplicationCommands.Cut, cutFile, canCutFile
    ApplicationCommands.Paste, pasteFile, canPasteFile
  ]
```
And, in the XAML:
```xaml
<TreeView elmish:CommandBindings="FolderViewCommands"/>
```

Internally, the view model would need to query the list of UIElement and binding name pairs and match them to the list of routedCommands so appropriate CommandBindings can be created and added to the UIElements.

I'd like to know if this has any use for anyone beyond me, if there are any changes or improvements on top of what I stated, if there are any simpler methods than what I outlined, and if this would be worth implementing at all.

**Comment by 2sComplement** [comment]
Thanks for your suggestion, the implementation looks feasible but I am still unsure what is provided by this that can't be accomplished through plain old custom commands.  I can take another look if there is enough interest, but closing for now.
