### ISSUE TITLE
How are validation/error messages propagated back to a control?

### ISSUE THREAD

**Issue by huwman** [Prolucid/Elmish.WPF#19]
Great project :)

In my experiment I couldn't find a way to send error notifications via the binding. As a last resort I tried throwing exceptions in the setter function of a two-way binding, that also doesn't propagate back.

Looking at the code ViewModelBase doesn't implement INotifyDataErrorInfo.

How can this be achieved?

**Comment by 2sComplement** [comment]
Thanks! Haven't hit this requirement yet but it's a good one. Since `INotifyDataErrorInfo` is not implemented yet, could you track errors separately in your model and base the error/control style off of that, perhaps using a trigger? I will make a plan to implement error handling in the future.

**Comment by huwman** [comment]
I look forward to the support, thank you.
In the meanwhile I will find a work around to show errors.

**Comment by 2sComplement** [comment]
@huwman Great suggestion, this is now implemented.

**Comment by huwmanatee** [comment]
This is a great enhancement, thank you.

One thing though, changes to the model aren't propagated to the UI when using the validating binding. I can submit a pull request, it looks like a single missing line of code.

**Comment by 2sComplement** [comment]
Sure!

**Comment by huwmanatee** [comment]
I have submitted a [pull request](https://github.com/Prolucid/Elmish.WPF/pull/27).
