### ISSUE TITLE
Please add samples 

### ISSUE THREAD

**Issue by forki** [Prolucid/Elmish.WPF#2]
Thanks!

**Comment by 2sComplement** [comment]
There is a counter sample as part of this repo (not sure if you saw it), but I agree more samples would be worthwhile. Any suggestions/requests?

**Comment by forki** [comment]
yes saw that after I was able to built the sources.
I think it's fine for now. Maybe put it samples folder so that's separated

2017-06-25 15:52 GMT+02:00 Justin Sacks <notifications@github.com>:

**Comment by 2sComplement** [comment]
Moved samples to a samples folder and created a performance sample (WIP).
