### ISSUE TITLE
Howto bind to command for buttons in a list

### ISSUE THREAD

**Issue by Slesa** [Prolucid/Elmish.WPF#20]
Hi all,
To try out Elmish.WPF, I am writing a small starter tool, which has a configurable list of buttons which start programs when clicked.

In the elmish example, I found the line
`| NumberToText id -> { model with Items = model.Items |> List.map (fun i -> if i.Id = id then numberToText i else i)}`

Would that mean, I have to found the button in the list which was responsible for that event?
I think, I am still missing a link in my mindset. There should probably be a buttonUpdate method to handle this call. But I can't figure out how to do that. Has someone an example for that?

**Comment by 2sComplement** [comment]
The missing link is probably in the view where you need to pass in a `CommandParameter` identifying that specific button. This is done in the [performance example](https://github.com/Prolucid/Elmish.WPF/blob/master/src/Samples/Elmish.Samples.PerformanceViews/Item.xaml#L22). Note also the `RelativeSource` used in the `Command` binding.

**Comment by Slesa** [comment]
Ok, instead of the RelativeSource I used an ElementName to get right DataContext. So at least, I was on the right way ;)

So far, what I *think* I have understood, are the update methods. I take the messages, with their models, and tie it somehow together. In case of this execute function of a button, I am bubbeling up:
`
let buttonUpdate (model:ButtonModel) =
...  
let buttonListViewUpdate (msg: ButtonMsg) (model: ButtonListViewModel) =
  match msg with
  | ButtonPressed m -> buttonUpdate m; model
let update (msg: Msg) (model: Model) =
  match msg with
  | ButtonMsg m -> { model with ButtonListView = buttonListViewUpdate m model.ButtonListView }
`

What I do not have understood at all is the binding thing. I have a statusbar binding which updates the current time - works. I have the binding to display the buttons - works. 
I want to have the binding to execute a button clicked command and don't know whre to place it. My current source is

`
let statusBarViewBinding : ViewBindings<StatusBarModel, StatusBarMsg> =
  [ "Time" |> Binding.oneWay (fun m -> m.Time) ]

let buttonBinding : ViewBindings<ButtonModel, ButtonMsg> =
  [ "ButtonPressed" |> Binding.cmd (fun p m -> ButtonPressed m) ]

let buttonListViewBinding : ViewBindings<ButtonListViewModel, ButtonMsg> =
  [ "ButtonItems" |> Binding.oneWay (fun m -> m.ButtonModels)
    (* "ButtonPressed" |> Binding.model (fun m -> m) buttonBinding m ButtonPressed *) ]

 [ "StatusBar" |> Binding.model (fun m -> m.StatusBar) statusBarViewBinding StatusBarMsg
   "ButtonView" |> Binding.model (fun m -> m.ButtonListView) buttonListViewBinding ButtonMsg
   (*"ButtonPressed" |> Binding.model (fun m -> m buttonBinding ButtonMsg ) *) ]
`
If there is some documention to read for a betting understanding, please tell me.

**Comment by 2sComplement** [comment]
Typically you do not need a model/update per message. You can have a single model/update that handles simple states. More complex states can be broken down into sub states if necessary. Same thing applies to ViewBinding, which can be a single list per view.

For binding a button, you would simply bind the `Command` dependency property on the button to the name of your ViewBinding:
`<Button Command="{Binding ButtonPressed}" Content="Click"/>`

There are examples of this in the [samples](https://github.com/Prolucid/Elmish.WPF/tree/master/src/Samples) folder, and have a look at the [readme](https://github.com/Prolucid/Elmish.WPF/blob/master/README.md) as well. Hope this helps.

**Comment by Slesa** [comment]
I took now the ItemNumToText stuff from the example and tried until this worked. Then it was easy to switch to the call of the command. I find it still strange that I have to identify the model with an id, though.

It was a good hint to leave everything in one (ok, two) data contexts. This simplifies a lot. Thank you.
