### ISSUE TITLE
How to send subsequent messages?

### ISSUE THREAD

**Issue by Slesa** [Prolucid/Elmish.WPF#21]
As in another thread written, I have a list of buttons with their commands. When such a command is executed, I want to send a message to the status bar with either success or error message.

```
    let buttonUpdate (model:ButtonModel) =
        match model.Function with
        | Command cmd -> commandExecute cmd |> ignore
     sendMsg "Program executed"
```
Probably all I need is an example of `Cmd.performFunc`, I assume?

**Comment by 2sComplement** [comment]
You can use `Cmd.batch` to send multiple commands in one of your `update` cases.  It might help to read through the [elmish docs](https://fable-elmish.github.io/elmish/) and [elmish samples](https://github.com/fable-elmish).

**Comment by Slesa** [comment]
It is a little bit difficult to switch - from `Program.mkSimple` to `Program.mkProgram`, from `updateViews (msg: Msg) (model: Model)` to `updateViews (msg: Msg) (model: Model) : Model*Cmd<Msg>` ... 
at leat if you are not that familiar with neither Elmish nor F#.

May I could add the resulting example as a PR?

**Comment by 2sComplement** [comment]
It shouldn't be that difficult, just add `... , Cmd.none` (or another `Cmd` function, like `Cmd.ofMsg`, depending on the subsequent messages you want to send) to each of your update cases and that should take care of the signature.
