### ISSUE TITLE
How can I send messages / cmds from a ui control ?

### ISSUE THREAD

**Issue by Silv3rcircl3** [Prolucid/Elmish.WPF#22]
Hi, 

my problem is that I work with a grid where the `SelectedItems` property isn't updated, only the list changes but no `PropertyChanged` event is raised, so I have to use the `SelectionChanged` event without binding. 
 I thought about something like this, in the code behind of my user control, where `Program.Select` is the message type.
```fsharp
this.Grid.SelectionChanged 
 |> Event.map currentItems
 |> Event.map Enumerable.OfType<Service.Patient>
 |> Event.map (List.ofSeq >> Program.Select)
 |> Event.add dispatchToProgram
```

**Comment by 2sComplement** [comment]
Are you using a `Grid` or a `DataGrid`? Why can't you bind a command to the `SelectionChanged` property?

**Comment by Silv3rcircl3** [comment]
@2sComplement I wasn’t aweare that you can bind an event to a command, will try tit out later. Thanks for the hint, will close this one if it works.

**Comment by Silv3rcircl3** [comment]
@2sComplement  Works like a charm, thx!
