### ISSUE TITLE
Where would logs go? 

### ISSUE THREAD

**Issue by forki** [Prolucid/Elmish.WPF#3]
Program.withTrace - is that implemented? Where would it go to?

**Comment by 2sComplement** [comment]
It does work, you need to run your executable as a console application instead of a windows application and then you get a second console window that shows logs.

**Comment by forki** [comment]
yes already noticed in my PR. sorry for the noise

2017-06-25 15:52 GMT+02:00 Justin Sacks <notifications@github.com>:

**Comment by cmeeren** [comment]
I'd like to log as trace to the VS output window, without a secondary console window. Could this be implemented?
