### ISSUE TITLE
Commands take two arguments, the first is normally unused

### ISSUE THREAD

**Issue by dsyme** [Prolucid/Elmish.WPF#31]
The callbacks for Bindings.cmd and cmdIf and other callbacks take two arguments - the first being the object "sender" propagated from the view.

In Elmish.XamarinForms this sender was actually normally null (actually the boxed unit value) AFAICS and I've removed it.

See https://github.com/Prolucid/Elmish.WPF/blob/master/src/Elmish.WPF/Binding.fs#L10

Does anyone actually use this sender parameter in Elmish.WPF?  The programming model would become a bit simpler and less error-prone if we dropped it.

**Comment by dsyme** [comment]
The comparable types in Elmish.XamarinForms are here: https://github.com/dsyme/Elmish.XamarinForms/blob/master/Elmish.XamarinForms/Binding.fs#L6

**Comment by 2sComplement** [comment]
The first parameter is actually the `CommandParameter` in line with `ICommand.Execute(parameter:obj)`. This can be useful for multiple instances of controls (e.g. in a `ListView`) with a button that binds to a single command. Example [here](https://github.com/Prolucid/Elmish.WPF/blob/master/src/Samples/Elmish.Samples.PerformanceViews/Item.xaml#L22). Not sure if this applies in Xamarin or not but I imagine a similar mechanism would be needed there as well.

**Comment by dsyme** [comment]
@2sComplement Ah ok, thanks. I'll check Xamarin

**Comment by dsyme** [comment]
Thanks, getting this fixed in Elmish.XamarinForms
