### ISSUE TITLE
Support for Framework < 4.6.2

### ISSUE THREAD

**Issue by isaacabraham** [Prolucid/Elmish.WPF#8]
Is there a possibility to support 4.6.1 or lower? This would open up stock VS2015 users etc..

**Comment by isaacabraham** [comment]
Ignore this - closing.

**Comment by forki** [comment]
I already adressed that in my PR

2017-06-25 15:03 GMT+02:00 Isaac Abraham <notifications@github.com>:

**Comment by isaacabraham** [comment]
You can get around this by installing 4.7 on a VS2015 machine but yes, I wasn't sure if the bar really needed to be so high as a minimum.

**Comment by forki** [comment]
it's already 4.5 buddy.

**Comment by isaacabraham** [comment]
Yes, I know. When I raised the issue, the nuget package wasn't :-)

**Comment by BentTranberg** [comment]
@forki, when I create an F# 4.0 (FSharp.Core, 4.4.0.0) project on .NET Framework 4.5.2 in VS 2015, and then try to install Elmish.WPF v1.0.0-beta-2, I get the following error message.

Could not install package Elmish.WPF 1.0.0-beta-2. You are trying to install this package into a project that targets .NETFramework,Version=v4.5.2, but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I worked around this by upgrading the project to Framework 4.6.1, installing the package, then downgrade to 4.5.2 again. Not sure why that works, but the project runs fine.

**Comment by forki** [comment]
I only changed it here in the code. I'm not a maintainer. So I don't know if it went to nuget

**Comment by 2sComplement** [comment]
I hadn't updated the target framework in paket.template. Should be fixed in beta-3.
